/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.35
 * Generated at: 2025-03-15 08:37:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>About Us | Exotic Coffee</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tailwind CSS -->\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./stylesheets/general-sans.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./stylesheets/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-white text-gray-900 flex flex-col min-h-screen general-sans\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Navigation Bar -->\r\n");
      out.write("<nav class=\"top-0 left-0 w-full flex absolute justify-between items-center py-3 px-4 text-black z-10\">\r\n");
      out.write("    <h1 class=\"text-2xl font-bold\">Exotic Coffee.</h1>\r\n");
      out.write("    <ul class=\"flex space-x-6\">\r\n");
      out.write("        <li><a href=\"index.jsp\" class=\"font-semibold hover:text-gray-300\">Home</a></li>\r\n");
      out.write("        <li><a href=\"products\" class=\"font-semibold hover:text-gray-300\">Shop</a></li>\r\n");
      out.write("        <li><a href=\"about.jsp\" class=\"font-semibold hover:text-gray-300\">About Us</a></li>\r\n");
      out.write("        <li><a href=\"register.jsp\" class=\"font-semibold hover:text-gray-300\">Log In/Register</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- About Section -->\r\n");
      out.write("    <section class=\"max-w-5xl mx-auto px-6 pt-32 pb-12\">\r\n");
      out.write("        <h1 class=\"text-5xl font-bold mb-6\">ABOUT US.</h1>\r\n");
      out.write("        <p class=\"text-gray-600 text-lg leading-relaxed\">\r\n");
      out.write("            At Exotic Coffee, we are dedicated to sourcing and roasting the finest coffee beans from around the world. \r\n");
      out.write("            Our journey started with a passion for exceptional coffee, sustainability, and ethical sourcing.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\"text-gray-600 text-lg leading-relaxed mt-4\">\r\n");
      out.write("            Every cup tells a story, from the farmers who cultivate our beans to the roasters who bring out their unique flavors. \r\n");
      out.write("            We take pride in offering premium-quality coffee that elevates your daily experience.\r\n");
      out.write("        </p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Team Image -->\r\n");
      out.write("    <section class=\"w-full\">\r\n");
      out.write("        <img src=\"https://cdn.pixabay.com/photo/2017/08/01/13/31/coffee-2565442_1280.jpg\" class=\"w-full h-[400px] object-cover\" alt=\"Our Team\">\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Quote Section -->\r\n");
      out.write("    <section class=\"max-w-5xl mx-auto px-6 py-16 flex flex-col md:flex-row items-center gap-12\">\r\n");
      out.write("        <!-- Quote -->\r\n");
      out.write("        <div class=\"md:w-1/2 text-left\">\r\n");
      out.write("            <p class=\"text-2xl italic font-semibold\">\r\n");
      out.write("                \"Great coffee is more than just a drink, it’s an experience that connects people across the world.\"\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"text-gray-600 mt-4\">- John Doe, Founder</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Supporting Image -->\r\n");
      out.write("        <div class=\"md:w-1/2\">\r\n");
      out.write("            <img src=\"https://cdn.pixabay.com/photo/2021/04/22/02/36/barista-6197867_1280.jpg\" class=\"rounded-lg shadow-md\" alt=\"Barista\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"bg-black text-white text-center py-6\">\r\n");
      out.write("        <p>&copy; IM2073 Project | Joel & Chretienne.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
